function openDB(){return new Promise(function(r,j){var q=indexedDB.open('FavsSnapDB',1);q.onupgradeneeded=function(){try{q.result.createObjectStore('handles')}catch(e){}};q.onsuccess=function(){r(q.result)};q.onerror=function(){j(q.error)}})}
async function saveDirectoryHandle(h){var d=await openDB();return new Promise(function(r,j){var t=d.transaction('handles','readwrite');t.objectStore('handles').put(h,'dirHandle');t.oncomplete=function(){d.close();r()};t.onerror=function(){d.close();j(t.error)}})}
async function loadDirectoryHandle(){var d=await openDB();return new Promise(function(r,j){var t=d.transaction('handles','readonly');var q=t.objectStore('handles').get('dirHandle');q.onsuccess=function(){d.close();r(q.result||null)};q.onerror=function(){d.close();j(q.error)}})}

var HEADERS={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36','Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8','Accept-Language':'zh-CN,zh;q=0.9,en;q=0.8'};
function getImageFilename(u,i,a){if(!a)a=0;var p=new URL(u),e=p.pathname.split('.').pop()||'';if(!e||e.length>5)e='jpg';var h=md5(u).substring(0,8),x=a?'A'+String(a).padStart(2,'0')+'_':'';return'img_'+x+String(i).padStart(3,'0')+'_'+h+'.'+e}
function md5(s){var h=0;for(var i=0;i<s.length;i++){h=((h<<5)-h)+s.charCodeAt(i);h&=h}var x=Math.abs(h).toString(16).padStart(8,'0');return x+x+x+x}
function sanitizeFilename(t){var s=t.substring(0,50).replace(/[/\\]/g,'_');s=[...s].filter(function(c){return/[\w一-鿿 \-_]/.test(c)}).join('');return s||'wechat-article'}
function formatDateTime(){var n=new Date(),p=function(x){return String(x).padStart(2,'0')};return n.getFullYear()+'-'+p(n.getMonth()+1)+'-'+p(n.getDate())+' '+p(n.getHours())+':'+p(n.getMinutes())+':'+p(n.getSeconds())}
async function fetchArticleHtml(u){var r=await fetch(u,{headers:HEADERS});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text()}
function extractImageUrls(h,b){var d=new DOMParser().parseFromString(h,'text/html'),a=[];for(var im of d.querySelectorAll('img')){var s=im.getAttribute('src')||im.getAttribute('data-src');if(s)try{a.push(new URL(s,b).href)}catch(e){}}return a}

function extractArticleContent(h,u){var p=new DOMParser(),d=p.parseFromString(h,'text/html'),t='';var tt=d.querySelector('h1.rich_media_title')||d.querySelector('h2.rich_media_title');if(tt)t=tt.textContent.trim();else{var m=d.querySelector('meta[property="og:title"]');if(m)t=m.getAttribute('content')||''}if(!t)t='微信文章 - '+u;var c='';var cd=d.getElementById('js_content')||d.querySelector('.rich_media_content');if(cd)c=cd.outerHTML;else{for(var dv of d.querySelectorAll('.rich_media_area_primary')){var sc=dv.querySelector('section');if(sc){c=sc.outerHTML;break}}}if(!c)c='';var isS=false,st='',si=[];var td=p.parseFromString(c,'text/html'),tl=(td.body.textContent||'').trim().length;if(tl<20){var cm=h.match(/content_noencode:\s*'((?:[^'\\]|\\.)*)'/);if(cm){var rt=cm[1];rt=rt.replace(/\\x0a/g,'\n').replace(/\\n/g,'\n');rt=rt.replace(/\\x3c/g,'<').replace(/\\x3e/g,'>');rt=rt.replace(/\\x22/g,'"').replace(/\\x26/g,'&');var tx=p.parseFromString(rt,'text/html'),ct=(tx.body.textContent||'').trim();if(ct.length>20){isS=true;st=ct;var pi=h.indexOf('window.picture_page_info_list');if(pi>=0){var as=h.indexOf('[',pi),dp=0,ae=as;for(var i=as;i<Math.min(as+100000,h.length);i++){if(h[i]==='[')dp++;else if(h[i]===']'){dp--;if(dp===0){ae=i+1;break}}}var arr=h.substring(as,ae),re=/width:\s*'(\d+)'\s*\*\s*1,\s*height:\s*'(\d+)'\s*\*\s*1,\s*cdn_url:\s*'([^']*)'/g,m2;while((m2=re.exec(arr))!==null){var iu=m2[3].replace(/\\x26amp;/g,'&');if(iu)si.push(iu)}}}}}var a='';var nm=h.match(/nick_name:\s*'((?:[^'\\]|\\.)*)'/);if(nm)a=nm[1].replace(/\\x26/g,'&').trim();if(!a){var nt=d.querySelector('span.rich_media_meta_nickname');if(nt)a=nt.textContent.trim()}var pd='';var dt=d.querySelector('em.rich_media_meta_text');if(dt)pd=dt.textContent.trim();return{title:t,author:a,publishDate:pd,contentHtml:c,isSlideshow:isS,slideshowText:st,slideshowImages:si}}

function htmlToMarkdown(c,b,m){if(!c)return'';var d=new DOMParser().parseFromString(c,'text/html'),SKIP=new Set(['svg','style','script','mp-common-profile','mp-style-type','template','ellipse']);function ru(s){if(!s)return null;try{return new URL(s,b).href}catch(e){return null}}function bj(a){var r='';for(var i=0;i<a.length;i++){var p=a[i];if(r){var v=r;if(v.endsWith('\n')){if(!/^(- |\d+\.)/.test(p))r+='\n'}else if(!p.startsWith('\n'))r+=' '}r+=p}return r}function pe(e){if(e.nodeType===Node.TEXT_NODE){var t=e.textContent.trim();return t||null}if(e.nodeType!==Node.ELEMENT_NODE)return null;var n=e.tagName.toLowerCase();if(n==='img'){var s=e.getAttribute('src')||e.getAttribute('data-src');if(s){var f=ru(s);if(f&&m[f])return'!['+(e.getAttribute('alt')||'')+']('+m[f]+')'}return null}if(n==='pre'){var cd=e.querySelector('code');if(cd){var ls=[],chs=cd.childNodes;for(var i=0;i<chs.length;i++){var ch=chs[i];if(ch.nodeType===Node.TEXT_NODE){var t=ch.textContent.trim();if(t)ls.push(t)}else if(ch.tagName&&ch.tagName.toLowerCase()==='br')ls.push('');else if(ch.nodeType===Node.ELEMENT_NODE){var t=ch.textContent.trim();if(t)ls.push(t)}}return'\n```\n'+ls.join('\n')+'\n```\n\n'}return null}if(n==='code'){var t=e.textContent.trim();return t?'`'+t+'`':null}if(n==='strong'||n==='b'){var t=e.textContent.trim();return t?'**'+t+'**':null}if(n==='em'||n==='i'){var t=e.textContent.trim();return t?'*'+t+'*':null}if(/^h[1-6]$/.test(n)){var l=parseInt(n[1]),t=e.textContent.trim();return t?'#'.repeat(l)+' '+t+'\n\n':null}if(n==='p'||n==='section'||n==='div'){var mk=e.getAttribute('data-mpa-md-key')||'';if(mk.startsWith('heading-')&&/\d$/.test(mk)){var l=parseInt(mk.slice(-1)),t=e.textContent.trim();return t?'#'.repeat(l)+' '+t+'\n\n':null}if(mk==='blockquote'){var t=e.textContent.trim();return t?'> '+t+'\n\n':null}if(mk==='bullet-list'||mk==='ordered-list')return null;var ps=[];for(var i=0;i<e.childNodes.length;i++){var r=pe(e.childNodes[i]);if(r)ps.push(r)}return ps.length?bj(ps)+'\n\n':null}if(n==='ul'||n==='ol'){var its=[],idx=1;for(var i=0;i<e.children.length;i++){var li=e.children[i];if(li.tagName&&li.tagName.toLowerCase()==='li'){var t=li.textContent.trim();if(t){its.push(n==='ol'?(idx+'. '+t):('- '+t));idx++}}}return its.length?its.join('\n')+'\n':null}if(n==='blockquote'){var ls=e.textContent.split('\n');return ls.map(function(l){return'> '+l}).join('\n')+'\n\n'}if(n==='br')return'\n\n';if(n==='hr')return'\n---\n\n';if(SKIP.has(n))return null;var ps=[];for(var i=0;i<e.childNodes.length;i++){var r=pe(e.childNodes[i]);if(r)ps.push(r)}return ps.length?bj(ps):null}var mp=[];for(var i=0;i<d.body.childNodes.length;i++){var r=pe(d.body.childNodes[i]);if(r)mp.push(r)}var r=mp.join('');r=r.replace(/\n{3,}/g,'\n\n');return r.trim()}

var dirHandle=null,running=false;
var setupCard=document.getElementById('setup-card'),setupBtn=document.getElementById('setup-btn'),setupPath=document.getElementById('setup-path'),mainUi=document.getElementById('main-ui'),txtUrls=document.getElementById('txt-urls'),dirPath=document.getElementById('dir-path'),changeDirBtn=document.getElementById('change-dir-btn'),btnStart=document.getElementById('btn-start'),lblStatus=document.getElementById('lbl-status'),progressRow=document.getElementById('progress-row'),progressFill=document.getElementById('progress-fill'),lblPercent=document.getElementById('lbl-percent'),txtLog=document.getElementById('txt-log');
var IMG_DELAY_MS=500,IMG_MAX_RETRIES=3,IMG_RETRY_DELAY_MS=1000;

function init(){mainUi.classList.remove('hidden');setupCard.classList.add('hidden');loadDirHandle();autoFillCurrentTabUrl();chrome.tabs.onActivated.addListener(function(){autoFillCurrentTabUrl()});chrome.tabs.onUpdated.addListener(function(tabId,ci,tab){if(tab.active&&ci.url)autoFillCurrentTabUrl()});setupBtn.addEventListener('click',handleSetup);changeDirBtn.addEventListener('click',handleChangeDir);btnStart.addEventListener('click',startBatch)}
async function loadDirHandle(){dirHandle=await loadDirectoryHandle();if(dirHandle){dirPath.textContent=dirHandle.name;dirPath.title=dirHandle.name}else showSetup()}
async function autoFillCurrentTabUrl(){try{var tabs=await chrome.tabs.query({active:true,currentWindow:true}),tab=tabs[0];if(tab&&tab.url&&tab.url.includes('mp.weixin.qq.com'))txtUrls.value=tab.url}catch(e){}}
function showSetup(){mainUi.classList.add('hidden');setupCard.classList.remove('hidden')}
function showMain(){setupCard.classList.add('hidden');mainUi.classList.remove('hidden');dirPath.textContent=dirHandle?dirHandle.name:'';dirPath.title=dirHandle?dirHandle.name:''}
async function ensurePermission(){if(!dirHandle)return false;var o={mode:'readwrite'};if((await dirHandle.queryPermission(o))==='granted')return true;try{return(await dirHandle.requestPermission(o))==='granted'}catch(e){log('目录权限已过期，请点击「修改」按钮重新选择目录','warn');return false}}
async function handleSetup(){try{var h=await window.showDirectoryPicker({mode:'readwrite'});dirHandle=h;await saveDirectoryHandle(h);setupPath.textContent='已选择：'+h.name;setupPath.classList.remove('hidden');setTimeout(function(){showMain()},400)}catch(e){if(e.name!=='AbortError')log('选择目录失败：'+e.message,'error')}}
async function handleChangeDir(){try{var h=await window.showDirectoryPicker({mode:'readwrite'});dirHandle=h;await saveDirectoryHandle(h);dirPath.textContent=h.name;dirPath.title=h.name;log('保存目录已更新为：'+h.name,'info')}catch(e){if(e.name!=='AbortError')log('选择目录失败：'+e.message,'error')}}

async function startBatch(){if(running)return;if(!dirHandle){log('请先选择保存目录','warn');return}if(!(await ensurePermission()))return;var raw=txtUrls.value.trim();if(!raw){log('请先输入文章链接','warn');return}var urls=raw.split('\n').map(function(l){return l.trim()}).filter(Boolean);if(!urls.length){log('请先输入文章链接','warn');return}running=true;setRunning(true);clearLog();resetProgress(urls.length);var ok=0,fail=0;for(var i=0;i<urls.length;i++){var url=urls[i],idx=i+1;log('['+idx+'/'+urls.length+'] 抓取：'+url,'dim');try{var h=await fetchArticleHtml(url),a=extractArticleContent(h,url),iu,md,st=sanitizeFilename(a.title);if(a.isSlideshow){iu=a.slideshowImages;var im=await downloadImages(iu,idx,st),ps=[];if(a.slideshowText.trim())ps.push(a.slideshowText.trim());for(var j=0;j<iu.length;j++){var u=iu[j];if(im[u])ps.push('\n![]('+im[u]+')')}md=ps.join('\n\n')}else{iu=extractImageUrls(a.contentHtml,url);var im=await downloadImages(iu,idx,st);md=htmlToMarkdown(a.contentHtml,url,im)}await saveMarkdown(a,url,md);log('  标题：'+a.title);log('  作者：'+(a.author||'—')+'          图片：'+iu.length+' 张  类型：'+(a.isSlideshow?'贴图文章':'普通文章'));log('  保存完成','success');ok++;updateProgress(idx,urls.length);lblStatus.textContent='正在抓取 '+idx+'/'+urls.length}catch(e){log('  抓取失败：'+e.message,'error');fail++}}var tag=fail===0?'success':'warn';log('\n完成 — 成功 '+ok+'，失败 '+fail,tag);lblStatus.textContent='完成 — 成功 '+ok+'，失败 '+fail;setProgress(100);setRunning(false)}

async function downloadImages(iu,ai,at){var m={};if(!iu.length)return m;var id,ad;try{id=await dirHandle.getDirectoryHandle('images',{create:true});ad=await id.getDirectoryHandle(at,{create:true})}catch(e){log('  无法创建 images 目录：'+e.message,'error');return m}var seen=new Set(),d=0,f=0,fu=[];for(var i=0;i<iu.length;i++){var u=iu[i];if(seen.has(u))continue;seen.add(u);var fn=getImageFilename(u,i+1,ai),rp='images/'+at+'/'+fn,ok=await tryDownloadImage(u,ad,fn,IMG_MAX_RETRIES);if(ok){m[u]=rp;d++}else{f++;fu.push(u)}if(i<iu.length-1)await sleep(IMG_DELAY_MS)}if(f>0){log('  图片：成功 '+d+' / 失败 '+f,'warn');for(var j=0;j<Math.min(fu.length,3);j++)log('    失败：'+fu[j],'dim')}return m}

async function tryDownloadImage(u,id,fn,mr){var ss=[{headers:{'Referer':'https://mp.weixin.qq.com/'}},{headers:{}}];for(var a=1;a<=mr;a++){for(var s=0;s<ss.length;s++){try{var r=await fetch(u,ss[s]);if(!r.ok)continue;var b=await r.blob(),fh=await id.getFileHandle(fn,{create:true}),w=await fh.createWritable();await w.write(b);await w.close();return true}catch(e){}}if(a<mr)await sleep(IMG_RETRY_DELAY_MS*a)}return false}

function sleep(ms){return new Promise(function(r){setTimeout(r,ms)})}

async function saveMarkdown(a,u,md){var fm=['# '+a.title,''];if(a.author)fm.push('**作者**: '+a.author);if(a.publishDate)fm.push('**发布时间**: '+a.publishDate);fm.push('**原文链接**: '+u,'**抓取时间**: '+formatDateTime(),'','---','');var c=fm.join('\n')+'\n'+md,st=sanitizeFilename(a.title),fh=await dirHandle.getFileHandle(st+'.md',{create:true}),w=await fh.createWritable();await w.write(c);await w.close()}

function setRunning(o){running=o;btnStart.disabled=o}
function resetProgress(t){progressRow.classList.remove('hidden');setProgress(0)}
function setProgress(p){progressFill.style.width=p+'%';lblPercent.textContent=Math.round(p)+'%'}
function updateProgress(c,t){setProgress((c/t)*100)}
function clearLog(){txtLog.innerHTML=''}
function log(m,tag){var l=document.createElement('div');if(tag)l.className=tag;l.textContent=m;txtLog.appendChild(l);txtLog.scrollTop=txtLog.scrollHeight}

document.addEventListener('DOMContentLoaded',init);
